version: '3.4'
services:
  ecommerce-mysql:
    extends:
      file: mysql.yml
      service: ecommerce-mysql
  ecommerce:
    image: dimmxx/fullstack-springboot-angular-ecommerce:latest
    environment:
      SPRING_DATASOURCE_URL: spring.datasource.url=jdbc:mysql://ecommerce-mysql:3308/full-stack-ecommerce?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&serverTimezone=UTC
    ports:
      - 8080:8080

