version: '3.4'

services:
  ecommerce-mysql:
    image: mysql:latest
    container_name: ecommerce-mysql
    environment:
      MYSQL_ROOT_PASSWORD: remote
      MYSQL_DATABASE: full-stack-ecommerce
    ports:
      - "3308:3306"
