version: '3.8'
services:

  ecommerce-mysql:
     image: mysql:latest
     container_name: ecommerce-mysql
     environment:
        MYSQL_ROOT_PASSWORD: rootpw
        MYSQL_DATABASE: full-stack-ecommerce
        MYSQL_USER: ecommerce
        MYSQL_PASSWORD: remote
     ports:
        - 3308:3306
     security_opt:
        - seccomp:unconfined #fixing 'mbind operation not permitted' warning

  ecommerce:
     image: dimmxx/fullstack-springboot-angular-ecommerce:latest
     container_name: ecommerce-backend
     ports:
        - 8090:8090
     environment:
        - SPRING_DATASOURCE_URL=jdbc:mysql://ecommerce-mysql:3308/full-stack-ecommerce?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&serverTimezone=UTC

